name: develop-build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build Dlid.MiHome
      run: dotnet build Dlid.MiHome/Dlid.MiHome.csproj --configuration Release
    - name: Run Tests in Dlid.MiHome.Tests
      run: dotnet test Dlid.MiHome.Tests --configuration Release
  
